# Example 1 Dockerfile
#
# + Create image:
#
#   docker image build -t alvaroms/ejem1kotlindocker:v1 .
#
# + List image:
#
#   docker image list
#
#   alvaroms/ejem1kotlindocker   v1                  33460af20233        29 minutes ago      686MB
#
FROM openjdk:8-jdk-alpine
VOLUME /tmp
RUN mkdir /app
COPY . /app
WORKDIR /app
RUN /app/gradlew build
RUN mv /app/build/libs/*.jar /app/app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app/app.jar"]




